### ISSUE TITLE
porcupine does not work.

### ISSUE THREAD

**Issue by satt105** [kalliope-project/kalliope_trigger_porcupine#3]
porcupine doesn't work on the raspberry pi 3b+ at the moment I've tested with an already created model. 
``
Waiting for trigger detection
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Jarvis/resources/trigger/porcupine/porcupinedecoder.py", line 1                                                                                        00, in run
    sensitivities=self._sensitivities)
  File "/home/pi/Jarvis/resources/trigger/porcupine/porcupinebinding.py", line 6                                                                                        7, in __init__
    raise IOError("Could not find Porcupine's library at '%s'" % library_path)
OSError: Could not find Porcupine's library at '/home/pi/Jarvis/resources/trigge                                                                                        r/porcupine/lib/armv7l/libpv_porcupine.so'
``

**Comment by corus87** [comment]
I don't have a pi3 b + so I can't test it, but I will look into the problem.

**Comment by satt105** [comment]
Hello,Thank you for your work and your quick response, regarding the tests I can do them with my raspberry if you wish.
I wish you a good evening and I take care of yourself.

**Comment by corus87** [comment]
Hi, can you please give me the output for  ```uname -a``` of your raspberry?

**Comment by satt105** [comment]
``Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
``

**Comment by satt105** [comment]
then I saw because there wouldn't be the plugin for armv7l.

**Comment by corus87** [comment]
Can you rename the folder cortex-a7 in lib to ```armv7l``` and try again to launch porcupine

**Comment by satt105** [comment]
``
Waiting for trigger detection
[ERROR] keyword file belongs to a different version of the library
[ERROR] loading keyword file #0 failed with 'INVALID_ARGUMENT'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/Jarvis/resources/trigger/porcupine/porcupinedecoder.py", line 1                                                                                        00, in run
    sensitivities=self._sensitivities)
  File "/home/pi/Jarvis/resources/trigger/porcupine/porcupinebinding.py", line 1                                                                                        16, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]('Initialization failed')

``

**Comment by satt105** [comment]
here's the new mistake, I'm going to try and define a sensibility

**Comment by satt105** [comment]
Apparently the keyword is out of date.

**Comment by corus87** [comment]
Just try a keyword provided [here](https://github.com/kalliope-project/kalliope_trigger_porcupine/tree/master/example_keyword_files) they should work

**Comment by satt105** [comment]
it seems to work, but we can no longer create magic words for the trigger ourselves on https://console.picovoice.ai.

**Comment by corus87** [comment]
Unfortunately for the raspberry there was never an option to create own keywords only x86 platform... 
You can only use the provided keywords by porcupine.

**Comment by satt105** [comment]
thanks for that

**Comment by corus87** [comment]
You welcome. 
I let this open, until I pushed a fix.
